### PR TITLE
Fix build on Linux 6.4

### PR DESCRIPTION
**Pull request by ol-sergeyn**
This PR fixes modules build errors on Linux 6.4:
```
onload/src/include/ci/driver/chrdev.h: In function ‘create_chrdev_and_mknod’:
/usr/src/linux-headers-6.4.0-0-common/include/linux/export.h:27:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   27 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
onload/src/include/ci/driver/chrdev.h:88:29: note: in expansion of macro ‘THIS_MODULE’
   88 |   reg->class = class_create(THIS_MODULE, name);
      |                             ^~~~~~~~~~~
```
and
```
build/x86_64_linux-6.4.0-0-amd64/driver/linux_onload/tcp_helper_linux.c:49:43: error: ‘struct iov_iter’ has no member named ‘iov’; did you mean ‘__iov’?                                    
   49 |     return base_handler(iocb->ki_filp, v->iov, v->nr_segs);             \                                                                                                                                  
      |                                           ^~~        
```
---
Checked by building on kernels:
6.4.0-0-amd64
6.3.0-1-amd64
5.15.0-72-generic

### CODE REVIEW

**Review by ol-alexandra — APPROVED** [review]

**Review by jbondpre-amd — APPROVED** [review]
Thanks!
