### ISSUE TITLE
Onload DKMS fail to build in Ubuntu 24.04

### ISSUE THREAD

**Issue by zaufi** [Xilinx-CNS/onload#219]
I know it's not officially supported (yet?) but maybe smbd knows how to fix this?
```
/var/lib/dkms/openonload/8.1.2.26/build/build/x86_64_linux-6.8.0-31-generic/driver/linux_net/drivers/net/ethernet/sfc/ethtool.c:546:35: error: initialization of ‘int (*)(struct net_device *, struct ethtool_rxfh_param *)’ from incompatible pointer type ‘int (*)(struct net_device *, u32 *, u8 *, u8 *)’ {aka ‘int (*)(struct net_device *, unsigned int *, unsigned char *, unsigned char *)’} [-Werror=incompatible-pointer-types]
  546 |         .get_rxfh               = efx_ethtool_get_rxfh,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/openonload/8.1.2.26/build/build/x86_64_linux-6.8.0-31-generic/driver/linux_net/drivers/net/ethernet/sfc/ethtool.c:546:35: note: (near initialization for ‘efx_ethtool_ops.get_rxfh’)
/var/lib/dkms/openonload/8.1.2.26/build/build/x86_64_linux-6.8.0-31-generic/driver/linux_net/drivers/net/ethernet/sfc/ethtool.c:547:35: error: initialization of ‘int (*)(struct net_device *, struct ethtool_rxfh_param *, struct netlink_ext_ack *)’ from incompatible pointer type ‘int (*)(struct net_device *, const u32 *, const u8 *, const u8)’ {aka ‘int (*)(struct net_device *, const unsigned int *, const unsigned char *, const unsigned char)’} [-Werror=incompatible-pointer-types]
  547 |         .set_rxfh               = efx_ethtool_set_rxfh,
      |                                   ^~~~~~~~~~~~~~~~~~~~```

**Comment by ivatet-amd** [comment]
@zaufi Thank you for raising the issue. 👍

Could you check if the latest OpenOnload `master` works for you? I think this specific Netdriver kernel compat fix went into `master` with https://github.com/Xilinx-CNS/onload/commit/c552f701dc2f4fe5ea44878674d6c817a6ed82e9 and is scheduled for the next Onload 8.1 release.
